### ISSUE TITLE
Delete products when goes out of stock 

### ISSUE THREAD

**Issue by suraj-rathod** [Knawat/dropshipping-woocommerce-wpml-addon#6]
Delete all the products along with the translated product when delete out of stock product option will be enabled

For example, if the main language version of the product will remove so other translated language products will be removed when this Addon is enable

**Comment by HeshamIsmail** [comment]
The main feature is still not working in [#65](https://github.com/Knawat/dropshipping-woocommerce/issues/65) 

As soon as we get a new update on #65 we'll proceed with testing

**Comment by HeshamIsmail** [comment]
The translated products were deleted as soon as the product was archived from the original and translated supported languages.

The test has met the acceptance criteria.
